# name: "Deploy Infra"
# on:
#   push:
#     branches:
#       - main

# jobs:
#   build_deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: "Checkout"
#         uses: actions/checkout@v4

#       - name: "Copy Files"
#         uses: appleboy/scp-action@v0.1.7
#         with:
#           host: ${{ secrets.HOST}}
#           username: ${{ secrets.USERNAME }}
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           source: "."
#           target: "/root/infra"
#           debug: true
